In [1]:
import cv2 as cv
import numpy as np

In [2]:
img = cv.imread('images/city.jpeg')
cv.imshow('city image', img)

In [3]:
data=np.asarray(img)

print(data)
data.shape

[[[199 138 124]
  [201 142 127]
  [199 144 131]
  ...
  [217 221 226]
  [217 221 226]
  [217 221 226]]

 [[207 153 142]
  [208 156 144]
  [205 157 145]
  ...
  [217 221 226]
  [217 221 226]
  [217 221 226]]

 [[218 179 171]
  [217 180 172]
  [217 181 173]
  ...
  [217 221 226]
  [217 221 226]
  [217 221 226]]

 ...

 [[135 119 106]
  [136 121 102]
  [122 111  81]
  ...
  [ 49  54  55]
  [ 76  75  71]
  [126 123 115]]

 [[144 131 123]
  [158 145 129]
  [140 129 101]
  ...
  [ 41  37  26]
  [ 44  37  20]
  [ 69  62  42]]

 [[146 137 127]
  [133 126 107]
  [115 108  75]
  ...
  [ 71  63  46]
  [ 61  55  32]
  [ 47  40  13]]]


(615, 1000, 3)

In [4]:
newdata = data.reshape(1000,615,3)
newdata.shape

(1000, 615, 3)

In [5]:
cv.imshow('reshaped', newdata)


In [6]:
cv.imwrite('rehaped_image.jpg', newdata)

True

In [7]:
#5 functions of OpenCv

#converting image to gray scale
gray_img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
cv.imshow('gray', gray_img)

#blur
blur = cv.GaussianBlur(img, (3,3), cv.BORDER_DEFAULT)
cv.imshow('blur', blur)

#edge cascade(edge detection)
canny = cv.Canny(img, 125, 150)
cv.imshow('edge detection', canny)

#dilating the image
dilated_img = cv.dilate(canny, (7,7), iterations=3)
cv.imshow('dilated image', dilated_img)

#eroding image
eroded_img = cv.erode(dilated_img, (7,7), iterations=3)
cv.imshow('eroded image', eroded_img)

cv.waitKey(0)
cv.destroyAllWindows()



In [20]:
# 5 functions of numpy
print(np.sort(data))
print(np.sum(data))
print(np.cumsum(data))
print(np.mean(data))
print(np.array_split(newdata,2))

[[[124 138 199]
  [127 142 201]
  [131 144 199]
  ...
  [217 221 226]
  [217 221 226]
  [217 221 226]]

 [[142 153 207]
  [144 156 208]
  [145 157 205]
  ...
  [217 221 226]
  [217 221 226]
  [217 221 226]]

 [[171 179 218]
  [172 180 217]
  [173 181 217]
  ...
  [217 221 226]
  [217 221 226]
  [217 221 226]]

 ...

 [[106 119 135]
  [102 121 136]
  [ 81 111 122]
  ...
  [ 49  54  55]
  [ 71  75  76]
  [115 123 126]]

 [[123 131 144]
  [129 145 158]
  [101 129 140]
  ...
  [ 26  37  41]
  [ 20  37  44]
  [ 42  62  69]]

 [[127 137 146]
  [107 126 133]
  [ 75 108 115]
  ...
  [ 46  63  71]
  [ 32  55  61]
  [ 13  40  47]]]
214539158
[      199       337       461 ... 214539105 214539145 214539158]
116.2813864498645
[array([[[199, 138, 124],
        [201, 142, 127],
        [199, 144, 131],
        ...,
        [239, 234, 235],
        [239, 234, 235],
        [239, 234, 235]],

       [[239, 234, 235],
        [239, 234, 235],
        [239, 234, 235],
        ...,
        [237, 234, 226